name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Build and Push Docker Image
      run: |
        docker build -t your-dockerhub-username/your-app-image:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push your-dockerhub-username/your-app-image:latest

    - name: Deploy to Docker Swarm
      run: |
        ssh your_user@your_server_ip "docker stack deploy -c /path-to-your-docker-compose.yml your_stack_name"
